config/routes.rb
Rails.application.routes.draw do
    root to: 'books#top'
    resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path(@book.id)
    else
      @books = Book.all.order(created_at: :desc)
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to books_path(book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class ="actions">
    <%= f.submit "Update Book" %>
  </div>
<% end %>

<%= link_to "show", book_path(@book.id) %>
<%= '|' %>
<%= link_to "back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book_path(book) %></td>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
          <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure? = 本当に削除しますか?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>New book</h2>
  <%= form_with model:@book, url:'/books', local: true do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_area :title %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@bookcd ) %>
<%= '|' %>
<%= link_to "back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<%= link_to "Start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>